### ISSUE TITLE
Setup.hs doesn't compile

### ISSUE THREAD

**Issue by sternenseemann** [lehins/FailT#1]
Culprit is the following invalid CPP:

https://github.com/lehins/FailT/blob/13c17e37bc95c0985b45fbdf0972aad77e6f1456/Setup.hs#L6

**Comment by lehins** [comment]
Thank you. There was a bug in my template. I am really surprised I haven't run into any problems with Setup.hs being borked like that.

**Comment by sternenseemann** [comment]
LMK when this is released to hackage!

**Comment by lehins** [comment]
@sternenseemann It is already up. I've deprecated the previous version, just to avoid any surprises.
